dual_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  # 50
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController 
    joint: Waist_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: L_shoulder_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: L_shoulder_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: L_shoulder_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: L_elbow_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: R_shoulder_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint7_position_controller:
    type: position_controllers/JointPositionController
    joint: R_shoulder_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint8_position_controller:
    type: position_controllers/JointPositionController
    joint: R_shoulder_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint9_position_controller:
    type: position_controllers/JointPositionController
    joint: R_elbow_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint10_position_controller:
    type: position_controllers/JointPositionController
    joint: Head_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint11_position_controller:
    type: position_controllers/JointPositionController
    joint: Head_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint12_position_controller:
    type: position_controllers/JointPositionController
    joint: L_wrist_yaw_joint
    pid: {p: 40.0, i: 0.0, d: 8.0}
  joint13_position_controller:
    type: position_controllers/JointPositionController
    joint: R_wrist_yaw_joint
    pid: {p: 40.0, i: 0.0, d: 8.0}
  joint14_position_controller:
    type: position_controllers/JointPositionController
    joint: L_wrist_pitch_joint
    pid: {p: 40.0, i: 0.0, d: 8.0}
  joint15_position_controller:
    type: position_controllers/JointPositionController
    joint: R_wrist_pitch_joint
    pid: {p: 40.0, i: 0.0, d: 8.0}